services:
  app:
    container_name: ilacs-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}
        NEXT_PUBLIC_AI_API_URL: ${NEXT_PUBLIC_AI_API_URL:-}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL:-}
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env.production
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
