// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type {
  AppRoutes,
  LayoutRoutes,
  ParamMap,
  AppRouteHandlerRoutes,
} from "./routes.js";
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js";
import type { NextRequest } from "next/server.js";

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default:
    | React.ComponentType<{ params: Promise<ParamMap[Route]> } & any>
    | ((
        props: { params: Promise<ParamMap[Route]> } & any,
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default:
    | React.ComponentType<LayoutProps<Route>>
    | ((
        props: LayoutProps<Route>,
      ) =>
        | React.ReactNode
        | Promise<React.ReactNode>
        | never
        | void
        | Promise<void>);
  generateStaticParams?: (props: {
    params: ParamMap[Route];
  }) => Promise<any[]> | any[];
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata,
  ) => Promise<any> | any;
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport,
  ) => Promise<any> | any;
  metadata?: any;
  viewport?: any;
};

type RouteHandlerConfig<
  Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes,
> = {
  GET?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  POST?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  PUT?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  PATCH?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  DELETE?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  HEAD?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
  OPTIONS?: (
    request: NextRequest,
    context: { params: Promise<ParamMap[Route]> },
  ) => Promise<Response | void> | Response | void;
};

// Validate ../../../src/app/[locale]/(auth)/login/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login/admin">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(auth)/login/admin/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(auth)/login/carrier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login/carrier">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(auth)/login/carrier/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(auth)/login/operator/page.tsx
{
  type __IsExpected<
    Specific extends AppPageConfig<"/[locale]/login/operator">,
  > = Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(auth)/login/operator/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(auth)/login/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/register">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(auth)/register/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/(admin)/terminals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terminals">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/(admin)/terminals/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/(admin)/users/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/users/[id]">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/(admin)/users/[id]/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/(admin)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/users">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/(admin)/users/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/bookings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/bookings/new">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/bookings/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/bookings">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/bookings/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/carrier/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/carrier">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/carrier/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/fleet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/fleet">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/fleet/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/loggings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/loggings">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/loggings/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/operator/bookings/page.tsx
{
  type __IsExpected<
    Specific extends AppPageConfig<"/[locale]/operator/bookings">,
  > = Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/operator/bookings/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/operator/dashboard/page.tsx
{
  type __IsExpected<
    Specific extends AppPageConfig<"/[locale]/operator/dashboard">,
  > = Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/operator/dashboard/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/operator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/operator">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/operator/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/profile">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/profile/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/settings">> =
    Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/settings/page.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(auth)/auth/callback/route.ts
{
  type __IsExpected<
    Specific extends RouteHandlerConfig<"/[locale]/auth/callback">,
  > = Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(auth)/auth/callback/route.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(auth)/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific;
  const handler =
    {} as typeof import("../../../src/app/[locale]/(dashboard)/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}

// Validate ../../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific;
  const handler = {} as typeof import("../../../src/app/[locale]/layout.js");
  type __Check = __IsExpected<typeof handler>;
  // @ts-ignore
  type __Unused = __Check;
}
